#!/bin/sh

C='#ebdedd33'  # default
B='#32343766'  # blank
D='#ebdeddff'  # default
W='#fb4934bb'  # wrong
A='#b8bb26ff'  # key
V='#fabd2fbb'  # verifying

scrot /tmp/sc.png
convert /tmp/sc.png -resize 25% -filter Gaussian -define filter:sigma=5 -resize 400% -fill black -colorize 40%  /tmp/bg.png

i3lock \
--insidevercolor=$B   \
--ringvercolor=$V     \
\
--insidewrongcolor=$B \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$V        \
--wrongcolor=$W        \
--timecolor=$D        \
--datecolor=$D        \
--layoutcolor=$D      \
--keyhlcolor=$A       \
--bshlcolor=$W        \
\
--clock               \
--indicator           \
--timestr="%H:%M"  \
--datestr="%A, %m %Y" \
\
--time-font=terminus \
--date-font=terminus \
--layout-font=terminus \
--verif-font=terminus \
--wrong-font=terminus \
--timesize=12 \
--datesize=12 \
--layoutsize=12 \
--verifsize=12 \
--wrongsize=12 \
\
--bar-indicator \
--bar-orientation vertical \
--bar-base-width 10 \
--bar-position 2*h/3 \
--bar-max-height 10 \
--bar-width=100 \
--bar-periodic-step 10 \
--bar-color $C \
--bar-step 10 \
-i /tmp/bg.png
# --keylayout 2         \

# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# etc
